spring:
  datasource:
#    url: jdbc:postgresql://localhost/iit
#    username: user
#    password: pass
    url: jdbc:postgresql://localhost/iit
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      SECRET_KEY: SECRET_KEY
      SECRET_REFRESH_KEY: SECRET_REFRESH_KEY
